### ISSUE TITLE
geom_text_repel is not working in plotly while plotting the bubble maps

### ISSUE THREAD

**Issue by M-Emran** [plotly/plotly.R#2386] opened 2024-08-31 10:46 UTC
---
geom_text_repel is not working in plotly while plotting the bubble maps provided in the example by plotly: https://plotly.com/ggplot2/bubble-maps/

plot using plotly
![Screenshot from 2024-08-31 15 44 17](https://github.com/user-attachments/assets/3b3aed45-7fb9-4c9d-b5cd-26fccd2a43fa)

plot in ggplot2
![Screenshot from 2024-08-31 15 44 43](https://github.com/user-attachments/assets/76669a9d-17b4-48cf-895b-27eae0ab705e)

```r
library(plotly)
library(ggplot2)
library(dplyr)
library(maps)
library(ggrepel)

UK <- map_data("world") %>% filter(region=="UK")
data <- world.cities %>% filter(country.etc=="UK")


p <- ggplot() +
  geom_polygon(data = UK, aes(x=long, y = lat, group = group), fill="grey", alpha=0.3) +
  geom_point( data=data, aes(x=long, y=lat, alpha=pop)) +
  geom_text_repel( data=data %>% arrange(pop) %>% tail(10), aes(x=long, y=lat, label=name), size=5) +
  geom_point( data=data %>% arrange(pop) %>% tail(10), aes(x=long, y=lat), color="red", size=3) +
  theme_void() + ylim(50,59) + coord_map() +
  theme(legend.position="none")

ggplotly(p)

p

```

**Comment by trekonom** [comment] 2024-08-31 14:11
This is essentially a duplicate of #2018  and also the same as #2283 , #2185 and ... . As of the moment `geom_text_repel` is not supported by `plotly` and you should get a warning message

> geom_GeomTextRepel() has yet to be implemented in plotly.

about that.

**Comment by cpsievert** [comment] 2024-09-03 15:43
Duplicate of #566

**Closed by cpsievert** 2024-09-03 15:43 UTC
