### ISSUE TITLE
no output with ggplotly

### ISSUE THREAD

**Issue by JonasBrouillon** [plotly/plotly.R#1845] opened 2020-09-03 11:11 UTC
Hi,
I'm trying to convert a ggplot into a ggplotly object but that doesn't work. 
The ggplot object works fine, but I always have an error message when I want to use ggplotly, I didn't find any solution. 
```r
> a <-ggplot(ethsexe_all, aes(x = aged_rec, y = SR,color=Eth,group=Eth, background_image(img), inherit.aes = FALSE)) + geom_line(size=1.3)+ ggpomological::theme_pomological(base_family = "Ink Free",base_size = 12)+ facet_wrap(~Annee) + labs(subtitle = "Source : ISEE, Recensements 1996, 2009 et 2014", x="Groupe d'age quinquennal") +scale_y_continuous()+scale_x_discrete()+geom_hline(yintercept = 100,linetype="dashed")+scale_color_manual(values = c("#FBB4AE","#CCEBC5","#B3CDE3","#DECBE4"))

> plotly::ggplotly(a)
Error in FUN(X[[i]], ...) : 
  'options' must be a fully named list, or have no names (NULL)

```

**Comment by stragu** [comment] 2020-11-12 04:58
Hi @JonasBrouillon 

Could you provide us with a reproducible example? It is very hard to try and figure out the issue without working code.

I assume you are using `background_image()` from the ggpubr package? Many extensions of ggplot2 will not be automatically supported by ggplotly, so I wouldn't be surprised if that was the issue.

But one thing you can try is to put the `background_image(img)` _outside_ the`ggplot()` / `aes()` functions, as is shown in the documentation: https://rdrr.io/cran/ggpubr/man/background_image.html

**Comment by cpsievert** [comment] 2021-11-02 21:55
Closing due to lack of reproducible example

**Closed by cpsievert** 2021-11-02 21:55 UTC
