### ISSUE TITLE
stat_ecdf does not work

### ISSUE THREAD

**Issue by danton267** [plotly/plotly.R#2011] opened 2021-09-25 01:06 UTC
Following code creates thousands of squareds of squares, instead of one step-line.

```
library(plotly)
library(ggplot2)

df <- data.frame(
  x = c(rnorm(100, 0, 3), rnorm(100, 0, 10)),
  g = gl(2, 100)
)

p <- ggplot(df, aes(x)) +
      stat_ecdf(geom = "step")

ggplotly(p)
```

**Comment by cpsievert** [comment] 2021-11-02 15:31
Duplicate of https://github.com/plotly/plotly.R/issues/1377 and https://github.com/plotly/plotly.R/issues/1030

**Closed** 2021-11-02 15:54 UTC
Labels: ggplotly
