### ISSUE TITLE
New fucntions to be implemented

### ISSUE THREAD

**Issue by yoelii** [plotly/plotly.R#2384] opened 2024-08-28 13:47 UTC
I try to convert a ggtree to plotly but I obtain several warnings about functions not yet implemented : 

``` R
In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]],  ... :
  geom_GeomSegmentGGtree() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues
10: In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]],  ... :
  geom_GeomTextGGtree() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues
11: In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]],  ... :
  geom_GeomHilightRect() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues
12: In geom2trace.default(dots[[1L]][[6L]], dots[[2L]][[1L]],  ... :
  geom_GeomPointGGtree() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues
```

**Comment by MLopez-Ibanez** [comment] 2024-08-30 17:00
The community may need to fork `plotly.R` as it does not seem to be maintained any longer.

**Comment by cpsievert** [comment] 2024-09-03 15:42
Duplicate of #566

**Closed by cpsievert** 2024-09-03 15:42 UTC
